_wandb:
    value:
        cli_version: 0.21.0
        e:
            awkfnzypgjeq0ld01l4a4exwpo7and0j:
                codePath: test.ipynb
                codePathLocal: test.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "509877751808"
                        used: "204848652288"
                email: chadrack.mayamba-hatu@etu.univ-amu.fr
                executable: c:\Users\etulyon1\mecagent-technical-test\.venv\Scripts\python.exe
                git:
                    commit: dc94ef8cce16a7d45da9767fab42c0625ec10cb1
                    remote: https://github.com/Portfolio20224/mecagent-technical-test.git
                host: PE062990
                memory:
                    total: "16905965568"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\etulyon1\mecagent-technical-test\test.ipynb
                python: CPython 3.11.13
                root: c:\Users\etulyon1\mecagent-technical-test
                startedAt: "2025-07-10T00:34:57.962739Z"
                writerId: awkfnzypgjeq0ld01l4a4exwpo7and0j
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
            "3":
                - 2
                - 16
            "4": 3.11.13
            "5": 0.21.0
            "6": 4.53.1
            "8":
                - 1
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 4
epochs:
    value: 15
gradient_accumulation_steps:
    value: 4
lr:
    value: 3e-05
max_seq_length:
    value: 256
warmup_ratio:
    value: 0.1
weight_decay:
    value: 0.01
